.github/pull_request_template.md
Adding basic pull request template file.
=> IOD-132 - Pull Request Template

.github/workflows/CICD.yml
- removed automatic triggers from the CICD GitHub Action
=> removed automatic triggers

docker-compose.yml, package-lock.json, src/main.ts
=> IOD-187 Docker Hot Load on Code Diff

.github/helpers/application_health.sh, .github/helpers/deploy-api.sh, .github/workflows/dev-api-build-deploy.yaml, openshift/templates/citz-imb-slam-api/dc.yaml
=> IOD-115 - Git Action to build/deploy to DEV

.github/workflows/dev-api-build-deploy.yaml, docker-compose.yml
=> IOD-115 Follow-up: Cleaning Docker Compose

.github/workflows/dev-api-build-deploy.yaml
=> Troubleshooting Docker Tag

.github/workflows/dev-api-build-deploy.yaml
=> docker tag reducing repository URL

.github/workflows/dev-api-build-deploy.yaml
=> Typo and tag source image name update

.github/workflows/dev-api-build-deploy.yaml
=> updating docker push

.github/workflows/dev-api-build-deploy.yaml
=> removing duplication

.github/workflows/dev-api-build-deploy.yaml
=> remove typo from script name

.github/helpers/deploy-api.sh
=> forgot pipe

.github/helpers/deploy-api.sh
=> incorrect path

.github/helpers/deploy-api.sh
=> correct path to dc.yaml

openshift/templates/citz-imb-slam-api/dc.yaml
=> updating trigger location

.github/helpers/deploy-api.sh, openshift/templates/citz-imb-slam-api/dc.yaml
=> correcting namespace parameter

.github/helpers/deploy-api.sh, openshift/templates/citz-imb-slam-api/dc.yaml
=> templating the deployment config

openshift/templates/citz-imb-slam-api/dc.yaml
=> Updating Deployment Config Template

openshift/templates/citz-imb-slam-api/dc.yaml
=> Troubleshooting Deployment Bug

.github/workflows/dev-api-build-deploy.yaml
=> Troubleshooting

package-lock.json, package.json, src/app.module.ts, src/health/health.controller.ts, src/health/health.module.ts
=> IOD-194 Adding Health Check

.github/workflows/dev-api-build-deploy.yaml
=> Troubleshooting Image Push to TOOLS

.github/workflows/dev-api-build-deploy.yaml
=> Troubleshooting Docker Login to TOOLS

.github/workflows/test-api-deploy.yaml
=> IOD-116 Create Git ACtion for TEST deploy

.github/workflows/dev-api-build-deploy.yaml
=> Adding New Cluster Login to Dev Deploy

src/health/health.controller.ts
=> IOD-129 Readiness and Liveness Probe

openshift/templates/citz-imb-slam-api/dc.yaml
=> IOD-129 Updating API Deployment Config

src/health/health.controller.ts
{"status":"error","info":{},"error":{"nestjs-docs":{"status":"down","message":"connect ECONNREFUSED ::1:80"}},"details":{"nestjs-docs":{"status":"down","message":"connect ECONNREFUSED ::1:80"}}}
Receiving the following when attempting to ping google. I'm going to change it back to the suggested URI from the nest documentation until I can figure out whats going on.
=> IOD-129 Health Endpoint Updates

openshift/templates/citz-imb-slam-api/dc.yaml
=> Update image location, Remove automatic deploy trigger

.github/workflows/test-api-deploy.yaml
=> IOD-116 Git Action for API deploy to TEST

.github/workflows/test-api-deploy.yaml
=> IOD-116 TEST SA Password

openshift/templates/citz-imb-slam-api/dc.yaml
=> IOD-116 Updating DC Trigger

openshift/templates/citz-imb-slam-api/dc.yaml
=> IOD-116 Fixing identation error

package.json, src/app.module.ts
=> changed formatting

openshift/templates/citz-imb-slam-api/dc.yaml
=> Re-Adding Automatic Deploy on Image change

.github/helpers/deploy-api.sh, .github/workflows/dev-api-build-deploy.yaml, openshift/templates/citz-imb-slam-api/dc.yaml
=> IOD-116 Adding Tagging Strategy to Environment Deploy

openshift/templates/citz-imb-slam-api/dc.yaml
=> Debugging deployment

.github/workflows/dev-api-build-deploy.yaml
=> Removing branch from manual trigger

src/app.module.ts
=> removed duplicate imports

Dockerfile
=> IOD-191 Run migrations

Dockerfile
=> IOD-191  Typo

Dockerfile, openshift/templates/citz-imb-slam-api/dc.yaml, package.json
=> Dockerized Migrations

.github/helpers/deploy-api.sh
=> Remove Image Tag

.github/workflows/prod-api-deploy.yaml
=> IOD-117 Create Git Action for PROD Deploy

openshift/templates/citz-imb-slam-api/service.yaml
=> Updating Openshift Service Template

src/main.ts
=> changed api path

openshift/templates/citz-imb-slam-api/dc.yaml
=> Updating POSTGRES Reference in Deployment Config

.github/workflows/pull-request-auto-assign.yaml
=> Auto Assign Team Members to PR

openshift/templates/citz-imb-slam-api/dc.yaml
=> update dc.yml configuration

src/app.controller.ts, src/auth/auth.service.ts, src/migrations/1653489888337-users.ts, src/migrations/1654023676305-adminUsers.ts, src/users/user.entity.ts
- Updated user entity to add email
- Updated table to include email and altered unique constraint
- Updated login route to create user if they don't already exist
- Does the user table in each environment need to be recreated, or is that handled in the migration queries?
- Login route is called multiple times on loading of the page, seemingly simultaneously. Taken care of with a try/catch, but should this be dealt with properly in the front end?
Tested locally.
=> IOD-242 Keycloak nest update

src/migrations/1654023676305-adminUsers.ts
- Adds all team members as admin for testing 
=> Add admins with keycloak

.github/helpers/deploy-api.sh, .github/workflows/dev-api-build-deploy.yaml
=> Updating DEV Tagging Strategy

.github/workflows/test-api-deploy.yaml
=> Updating TEST Deployment Strategy

docker-compose.yml
- Updated pg-admin section to be named pg-admin instead of pgadmin.
=> Made docker-compose match readme command.

src/auth/auth.service.ts
- Forces email to lowercase during login route
Tested on local build
=> IOD-267 Ensure email is lowercase during login route
